[project]
name = "metric-officer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "pytest>=8.4.1",
    "ruff>=0.12.11",
    "wemake-python-styleguide>=1.4.0",
]
